#!/usr/bin/env bash

BRIGHTNESS=`cat /sys/class/leds/asus::screenpad/brightness`

icon() {
    bri=$(echo $((BRIGHTNESS*100/255)))
    
    if [[ "$bri" -gt "90" ]]; then
        echo "󰃠"
        elif [[ "$bri" -gt "50" ]]; then
        echo "󰃝"
        elif [[ "$bri" -gt "30" ]]; then
        echo "󰃟"
    else
        echo "󰃞"
    fi
}

getbri() {
    floor_val=
    float_val=$BRIGHTNESS
    floor_val=${float_val/.*}
    echo $floor_val
}

if [[ $1 == "--icon" ]]; then
    icon
    elif [[ $1 == "--value" ]]; then
    getbri
fi