#!/bin/bash

EWW="eww -c /home/ljmill/dotfiles/eww/isocat update"


while true; do
    sleep 1
    ${EWW} hour=images/numbers/H"$(date +%l)".png
    ${EWW} month=images/numbers/M"$(date +%m)".png
    ${EWW} day=images/numbers/D"$(date +%e)".png
    echo "images/numbers/$(date +%M).png"
    #wait
done