#!/bin/sh

workspaces() {
    workspaces=1,3,5,7,9
    stringliteral="(box :orientation \"v\" "
    # Looping over each workspace to construct a widget (string literal) to
    # pass back to Eww
    for val in ${workspaces//,/ }
    do
        if [[ $(bspc query -D -d focused --names | grep "$val") ]]; then 
            stringliteral+="(image :path \"images/ocube.png\") "
            continue
        elif [[ $(bspc query -D -d .occupied --names | grep "$val") ]]; then 
            stringliteral+="(image :path \"images/gcube.png\") "
            continue
        else
            stringliteral+="(image :path \"images/ncube.png\") "
        fi
    done

    echo "$stringliteral)"
}

workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done


