#!/bin/sh

STATUS=$(dunstctl is-paused)

if [ $STATUS == "false" ]; then
    dunstctl set-paused true
    eww -c ~/.config/eww/bar update dnd-color="#734bd8"
    eww -c ~/.config/eww/bar update dnd-status="On"
else
    dunstctl set-paused false
    notify-send --urgency=normal "Do Not Disturb" "Do not Disturb has been turned off!"
    eww -c ~/.config/eww/bar update dnd-color="rgba(255,255,255,0.15)"
    eww -c ~/.config/eww/bar update dnd-status="Off"
fi