#!/bin/sh

LEVEL=`cat /sys/class/leds/asus::kbd_backlight/brightness`

if [[ $LEVEL -eq 0 ]]; then
    echo 1 > /sys/class/leds/asus::kbd_backlight/brightness
    eww -c ~/.config/eww/bar update keybright-image="images/kbb1.png"
elif [[ $LEVEL -eq 1 ]]; then
    echo 2 > /sys/class/leds/asus::kbd_backlight/brightness
    eww -c ~/.config/eww/bar update keybright-image="images/kbb2.png"
elif [[ $LEVEL -eq 2 ]]; then
    echo 0 > /sys/class/leds/asus::kbd_backlight/brightness
    eww -c ~/.config/eww/bar update keybright-image="images/kbb0.png"
fi