#!/bin/sh

workspaces() {
    # Replace the value of this variables ( 2,4,6,8,0 ) with the numbers
    # defined in your bspwmrc with regards to:
    # A. The numbers you use for your workspaces on your secondary monitor
    workspaces=2,4,6,8,0
    stringliteral="(box	:class \"works\" :orientation \"v\"	:halign \"center\"	:valign \"start\" :space-evenly \"false\" :spacing \"-5\" "

    focusedcolor="\"focused-work\" "
    unfocusedcolor="\"unfocused-work\" "

    occupiedicon="\"󰿦\""
    unoccupiedicon="\"󰔌\""


    # Looping over each workspace to construct a widget (string literal) to
    # pass back to Eww
    for val in ${workspaces//,/ }
    do
    stringliteral+="(button :class "
        if [[ $(bspc query -D -d focused --names | grep "$val") ]]; then 
            stringliteral+=${focusedcolor}
        else
            stringliteral+=${unfocusedcolor}
        fi

        stringliteral+=":onclick \"bspc desktop -f $val\" "

        if [[ $(bspc query -D -d .occupied --names | grep "$val") ]]; then 
            stringliteral+=${occupiedicon}
        else
            stringliteral+=${unoccupiedicon}
        fi
        stringliteral+=") "
    done

    echo "$stringliteral)"
}

workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done


