#! /bin/sh

# Autostart --------------------------------------------------
killall "blueberry-obex-agent"
killall "blueberry-tray"
killall "picom"
killall "dunst"
killall "nm-applet"
killall "firewall-applet"
killall "nitrogen"
killall "xapp"
killall "ati-spi"
killall "xfce4-power-manager"

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Dunst
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# wal -R
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
pgrep -x picom > /dev/null || picom --experimental-backends &
# Network Applet
nm-applet --indicator &
# Power Manager
xfce4-power-manager &
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Fix touchscreens
xinput map-to-output 'ELAN9008:00 04F3:2C1A' eDP-1 &
xinput map-to-output 'ELAN9009:00 04F3:2C1B' DP-3 &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# Config -----------------------------------------------------

bspc monitor eDP-1 -d 1 3 5 7 9
bspc monitor DP-3 -d 2 4 6 8 0 

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         10

bspc config split_ratio          0.52
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false

bspc config focused_border_color        "#B4BEFE"
bspc config normal_border_color         "#1e1e2e"
bspc config active_border_color         "#1e1e2e"
bspc config presel_feedback_color		"#008ce3"

# bsp-layout -------------------------------------------------

# Set bsp-layout for each workspace
for val in {0..9}; do
    bsp-layout set tiled $val
done