#! /bin/sh

## Autostart -------------------------------------------------#
killall "blueberry-obex-agent"
killall "blueberry-tray"
killall "picom"
killall "dunst"
killall "nm-applet"
killall "firewall-applet"
killall "nitrogen"
killall "xapp"
killall "ati-spi"
killall "xfce4-power-manager"
killall "eww"

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Polybar
#~/.config/polybar/launch.sh &
# Eww
# $HOME/.local/bin/eww -c $HOME/dotfiles/eww/old/bar --restart open-many bottom-bar bar &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# wal -R
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
#pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x picom > /dev/null || picom &
# Network Applet
nm-applet --indicator &
# Power Manager
xfce4-power-manager &
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# Fix touchscreens
xinput map-to-output 'ELAN9008:00 04F3:2C1A' eDP1 &
xinput map-to-output 'ELAN9009:00 04F3:2C1B' DP3 &

## Get colors from .Xresources -------------------------------#
# xrdb ~/.Xresources
# getcolors() {
# 	FOREGROUND=$(xrdb -query | grep 'foreground:'| head -n 1 | awk '{print $NF}')
# 	BACKGROUND=$(xrdb -query | grep 'background:'| head -n 1 | awk '{print $NF}')
# 	BLACK=$(xrdb -query | grep 'color0:'| head -n 1 | awk '{print $NF}')
# 	RED=$(xrdb -query | grep 'color1:'| head -n 1 | awk '{print $NF}')
# 	GREEN=$(xrdb -query | grep 'color2:'| head -n 1 | awk '{print $NF}')
# 	YELLOW=$(xrdb -query | grep 'color3:'| head -n 1 | awk '{print $NF}')
# 	BLUE=$(xrdb -query | grep 'color4:'| head -n 1 | awk '{print $NF}')
# 	MAGENTA=$(xrdb -query | grep 'color5:'| head -n 1 | awk '{print $NF}')
# 	CYAN=$(xrdb -query | grep 'color6:'| head -n 1 | awk '{print $NF}')
# 	WHITE=$(xrdb -query | grep 'color7:'| head -n 1 | awk '{print $NF}')
# }
# bspcolors
# bspdunst
# getcolors


bspc monitor eDP1 -d 1 3 5 7 9
bspc monitor DP3 -d 2 4 6 8 0 

bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false

# Border
bspc config focused_border_color        "$BLUE"
bspc config normal_border_color         "$BACKGROUND"
bspc config active_border_color         "$BLUE"
bspc config presel_feedback_color		"$GREEN"

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

