#!/bin/sh

STATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"

if [[ $STATUS == "no" ]]; then
    rfkill block 0
    notify-send --urgency=normal "Airplane Mode" "Airplane mode has been turned on!"
    eww -c ~/.config/eww/bar update airplane-status="On"
    eww -c ~/.config/eww/bar update airplane-icon="󰀝"
else
    rfkill unblock 0
    notify-send --urgency=normal "Airplane Mode" "Airplane mode has been turned off!"
    eww -c ~/.config/eww/bar update airplane-status="Off"
    eww -c ~/.config/eww/bar update airplane-icon="󰀞"
fi