#!/bin/sh


eww="ewwl -c /home/ljmill/dotfiles/eww/test"


update() {
    cur_track=$(playerctl -p spotify,$any,mpd,firefox,chromium,brave metadata xesam:title)
    eww_track=$(ewwl -c ~/dotfiles/eww/test state | grep music-title | sed 's/music-title: //')

    if [[ "$cur_track" == "${eww}_track" ]]; then
        exit
    else 
        update_artist
        update_title
        update_art
    fi
}

update_art() {
    tmp_dir="$HOME/dotfiles/eww/test/images"
    tmp_temp_path=$tmp_dir/temp.png

    artlink="$(playerctl -p spotify,$any,mpd,firefox,chromium,brave metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
    artFromBrowser=$(playerctl metadata mpris:artUrl | sed 's/file:\/\///g')

    if [ $(playerctl -p spotify,%any,firefox,chromium,brave,mpd metadata mpris:artUrl) ]; then
        curl -s "$artlink" --output $tmp_temp_path
        ${eww} update music-art=$tmp_tmp_path
    elif [[ -n $artFromBrowser ]]; then
        cp $artFromBrowser $tmp_temp_path
        ${eww} update music-art=$tmp_temp_path
    else
        ${eww} update music-art=images/default-music.svg
    fi
}

update_title() {
    FORMAT="{{ title }}"
    STATUS=$(playerctl status 2>/dev/null)
    
    if [[ "$STATUS" == "Stopped" ]]; then
        STATUS="Nothing is playing"
    elif [[ "$STATUS" == "No players found" ]]; then
        STATUS="Nothing is playing"
    else
        STATUS=$(playerctl metadata --format \"$FORMAT\")
    fi

    ${eww} update music-title=$STATUS
}

update_artist() {
    FORMAT="{{ artist }}"
    STATUS=$(playerctl status 2>/dev/null)
    EXIT_CODE=$?

    if [[ "$STATUS" == "Stopped" ]]; then
        STATUS="No Artist"
    elif [[ "$STATUS" == "No players found" ]]; then
        $STATUS="No Artist"
    else
        STATUS=$(playerctl metadata --format \"$FORMAT\")
    fi

    ${eww} update music-artist=$STATUS
}

update_length() {
    FORMAT="{{ duration(position) }} / {{ duration(mpris:length) }}"
    STATUS=$(playerctl status 2>/dev/null)

    if [[ "$STATUS" == "Stopped" ]]; then
        STATUS="--:-- / --:--"
        ${eww} update music-pp="󰐊"
    elif [[ "$STATUS" == "No players found" ]]; then
        STATUS="--:-- / --:--"
        ${eww} update music-pp="󰐊"
    elif [[ "$STATUS" == "Paused" ]]; then
        STATUS=$(playerctl metadata --format \"$FORMAT\")
        ${eww} update music-pp="󰐊"
    else
        STATUS=$(playerctl metadata --format \"$FORMAT\")
        ${eww} update music-pp="󰏤"
    fi

    echo $STATUS
    update
}

if [[ "$1" == "--length" ]]; then
    update_length
fi