#!/bin/bash

temp_path=/tmp/temp.png

if [ ! -d $tmp_dir ]; then
	mkdir -p $tmp_dir
fi

artlink="$(playerctl -p spotify,$any,mpd,firefox,chromium,brave metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
artFromBrowser=$(playerctl metadata mpris:artUrl | sed 's/file:\/\///g')

if [ $(playerctl -p spotify,%any,firefox,chromium,brave,mpd metadata mpris:artUrl) ]; then
	# curl -s "$artlink" --output /tmp/
	# echo $temp_path
	# Actual temp copy
	album="$(playerctl metadata --format "{{ album }}" | sed 's/[^a-zA-Z0-9]//g')"
	curl -s "$artlink" --output /tmp/$album.png
	echo /tmp/$album.png

elif [[ -n $artFromBrowser ]]; then
	cp $artFromBrowser $temp_path
	echo $temp_path
else
	echo images/default-music.svg
fi