#!/bin/sh

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"
    EWW_BIN="$HOME/.local/bin/eww"

    run() {
        ${EWW_BIN} -c $HOME/.config/eww/bar open calendar
    }

    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        run
    else
        ${EWW_BIN} -c $HOME/.config/eww/bar close calendar
        rm "$LOCK_FILE"
    fi
}

if [ "$1" = "launcher" ]; then
    wofi --show drun -o eDP-1
elif [ "$1" = "wifi" ]; then
    alacritty -e nmtui
elif [ "$1" = "audio" ]; then
    pavucontrol
elif [ "$1" = "calendar" ]; then
    calendar
elif [ "$1" = "bluetooth" ]; then
    blueberry
fi
