#!/bin/sh

eww="ewwl -c /home/ljmill/dotfiles/eww/hyprbar"

${eww} update b_vitals=false
${eww} update b_apps=false
${eww} update b_folders=false
${eww} update b_websites=false
${eww} update b_power=false
${eww} update b_info=false

${eww} update button-one-color="rgba(255,255,255,0.2);"
${eww} update button-two-color="rgba(255,255,255,0.2);"
${eww} update button-three-color="rgba(255,255,255,0.2);"
${eww} update button-four-color="rgba(255,255,255,0.2);"
${eww} update button-five-color="rgba(255,255,255,0.2);"

# stop multiple trays from opening at once
if [[ $($eww state | grep true ) ]]; then
    exit
fi

if [[ "$1" == "--1" ]]; then
    ${eww} update selection="images/nsw/mosttop.png"
    ${eww} update b_vitals=true
    ${eww} update button-one-color="rgba(0,0,0,0.7);"
    #text-shadow: 0px 0px 10px #734bd8;"
    elif [[ "$1" == "--2" ]]; then
    ${eww} update selection="images/nsw/top.png"
    ${eww} update b_folders=true
    ${eww} update button-two-color="rgba(0,0,0,0.7);" 
    #text-shadow: 0px 0px 5px #d8af4b;"
elif [[ "$1" == "--3" ]]; then
    ${eww} update selection="images/nsw/middle.png"
    ${eww} update b_apps=true
    ${eww} update button-three-color="rgba(0,0,0,0.7);" 
    #text-shadow: 0px 0px 5px #4bd8a2;"
elif [[ "$1" == "--4" ]]; then
    ${eww} update selection="images/nsw/bottom.png"
    ${eww} update b_websites=true
    ${eww} update button-four-color="rgba(0,0,0,0.7);" 
    #text-shadow: 0px 0px 10px #9ed84b;"
elif [[ "$1" == "--5" ]]; then
    ${eww} update selection="images/nsw/mostbottom.png"
    ${eww} update b_power=true
    ${eww} update button-five-color="rgba(0,0,0,0.7);" 
    #text-shadow: 0px 0px 5px #d84b4f;"
elif [[ "$1" == "--6" ]]; then
    ${eww} update selection="images/nsw/tray.png"
    ${eww} update b_info=true
    #${eww} update button-six-color="rgba(0,0,0,0.7);" 
    #text-shadow: 0px 0px 5px #d84b4f;"
fi
