#!/bin/sh

STATUS=$(dunstctl is-paused)

if [ $STATUS == "false" ]; then
    dunstctl set-paused true
    eww -c ~/dotfiles/eww/iso update dnd-icon="dnd1"
else
    dunstctl set-paused false
    notify-send --urgency=normal "Do Not Disturb" "Do not Disturb has been turned off!"
    eww -c ~/dotfiles/eww/iso update dnd-icon="dnd0"
fi