#!/bin/sh

LEVEL=`cat /sys/class/leds/asus::kbd_backlight/brightness`

icon() {
    if [[ $LEVEL -eq 0 ]]; then
        echo "images/kbb0.png"
    elif [[ $LEVEL -eq 1 ]]; then
        echo "images/kbb1.png"
    elif [[ $LEVEL -eq 2 ]]; then
        echo "images/kbb2.png"
    fi
}

toggle() {
    if [[ $LEVEL -eq 0 ]]; then
        echo 1 > /sys/class/leds/asus::kbd_backlight/brightness
        LEVEL=1
    elif [[ $LEVEL -eq 1 ]]; then
        echo 2 > /sys/class/leds/asus::kbd_backlight/brightness
        LEVEL=2
    elif [[ $LEVEL -eq 2 ]]; then
        echo 0 > /sys/class/leds/asus::kbd_backlight/brightness
        LEVEL=0
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
fi