#!/bin/bash

COLORFILE="/home/ljmill/dotfiles/eww/quixotic/theme.scss"
eww="/home/ljmill/dotfiles/bin/eww -c /home/ljmill/dotfiles/eww/quixotic"

if [[ "$1" == "2" ]]; then
    sed -i 's/primary1/primary_temp/' $COLORFILE
    sed -i 's/secondary1/secondary_temp/' $COLORFILE

    sed -i 's/primary2/primary1/' $COLORFILE
    sed -i 's/secondary2/secondary1/' $COLORFILE

    sed -i 's/primary_temp/primary2/' $COLORFILE
    sed -i 's/secondary_temp/secondary2/' $COLORFILE

    sleep 0.1

    MAINCOLOR="$(cat $COLORFILE | grep primary1 | awk '{ print $2 }' | sed -E 's/\$|;//g')"
    ${eww} update color=$MAINCOLOR
elif [[ "$1" == "3" ]]; then
    sed -i 's/primary1/primary_temp/' $COLORFILE
    sed -i 's/secondary1/secondary_temp/' $COLORFILE

    sed -i 's/primary3/primary1/' $COLORFILE
    sed -i 's/secondary3/secondary1/' $COLORFILE

    sed -i 's/primary_temp/primary3/' $COLORFILE
    sed -i 's/secondary_temp/secondary3/' $COLORFILE

    sleep 0.1

    MAINCOLOR="$(cat $COLORFILE | grep primary1 | awk '{ print $2 }' | sed -E 's/\$|;//g')"
    ${eww} update color=$MAINCOLOR
fi